name: Snyk GHA
on: 
    workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  show-message-job:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Display a simple message
        run: echo "Hello from a GitHub Actions workflow!"
