name: "Snyk Scan CLI"

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'  # Include any branch starting with demo

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Scan CLI'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk OS
      - name: Run Snyk OS
        run: |
          snyk test
        continue-on-error: false
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test 
        continue-on-error: false

